### ISSUE TITLE
运行结果好像有些问题

### ISSUE THREAD

**Issue by Syopain** [Whotakesmyname/ChinesePokerGame#1]
我用8888炸不了QQ，或者是我操作有问题吗？

测试数据如下：

请输入地主(玩家)手牌，如OJQKAE(10、J、Q、K、A)
【Info】10使用英文字母O代替，小王Y，大王Z；回车结束输入：
YZQQKK22

请输入农民手牌，如OJQKAE(10、J、Q、K、A)
【Info】10使用英文字母O代替，小王Y，大王Z；回车结束输入：
888822OO

请输入上家出牌；如果是玩家先出，请直接回车以跳过。

【Info】计算完成！共花费0.000779秒
【Info】地主必胜

请出{Q Q}
请输入对方出牌：
8888
【Error】对方无法这样出，请重新输入。
请输入对方出牌：
8 8 8 8
【Error】对方无法这样出，请重新输入。

**Comment by Whotakesmyname** [comment]
你发现了Bug！

你的操作没有问题，初步看这是一个牌型比较处理上的bug。有段时间没碰这个项目了，我会着手修复的。

谢谢

**Comment by Whotakesmyname** [comment]
代码已经修改，新的release已经发布。你的case表现正常。 @Syopain

**Comment by Whotakesmyname** [comment]
Fixed. 0e0bc62

**Comment by Syopain** [comment]
@Whotakesmyname 好像还是有些bug，8炸被对2打了：

请出{K K}
请输入对方出牌：
8888

请出{2 2}

**Comment by Whotakesmyname** [comment]
插入牌型有误。这样应该好了。你的case现在结果是玩家没有必胜策略。

**Comment by Whotakesmyname** [comment]
1b30333 Fixed problem caused by wrong pattern types.
