### ISSUE TITLE
运行exe出现乱码

### ISSUE THREAD

**Issue by sudaoer** [Whotakesmyname/ChinesePokerGame#2]
![image](https://user-images.githubusercontent.com/73027060/123442927-fba5e300-d607-11eb-9a6e-5350dec425c7.png)
如图
版本1.3.1
推测是utf-8和gb2312的问题
但是我是个小白，编译报错不会修（vs2019）
<img width="384" alt="Snipaste_2021-06-25_22-56-13" src="https://user-images.githubusercontent.com/73027060/123443730-be8e2080-d608-11eb-80d5-36048bbb0387.png">
 顺便求教下如何编译

**Comment by Whotakesmyname** [comment]
尝试打开一个新的cmd窗口先`chcp 65001`或者`chcp 936`再在该处执行.exe试试。

关于编译，从截图我没得到什么有用的信息 *（这个中译让我更看不懂了）* ，我只能盲猜你是没有include Boost库。

这个玩具项目有点久了，当时有些图样有些设计也不是很满意，比如内存管理的设计和可以解除的对Boost的依赖。前段时间有重构但因为种种原因进度停滞了（见dev分支），之后会改成cmake构建而不是基于Visual Studio。~~*说这么多其实就是不想对当前版本的编译负责！*~~

如果你的编译问题真是没有include Boost库的话，我想如何装这个库的教程应该很多。（项目只用到了头文件，可以免去编译Boost的烦恼，希望这能让你感到relief）。如果不是这个原因的话，恐怕暂时爱莫能助。***但最近又闲了，说不定明天就更新了呢？***

**Comment by sudaoer** [comment]
感谢作者大大的回复。
![image](https://user-images.githubusercontent.com/73027060/123494590-f91cab00-d652-11eb-91d8-686cec426f01.png)
我试了下用mingw编译，报了这些错
boost库我已经扔到include下了

**Comment by Whotakesmyname** [comment]
Try `g++ ./*.cpp -o ChinesePokerGame.exe --std=c++17 -O3`. 另外修改此命令把Boost库include进来。
